---
title: "Untitled"
format: html
editor: visual
---

```{r}
library(UWCCC.misc) #For makeExtFilePath
date_tag = basename(getwd())
```

## Read in train

```{r}
train <- read.csv("../../../data/train.csv", stringsAsFactors=FALSE)
```


```{r, fig.height=40, fig.width=5}
boxplot(score~ref_short+alt_short, data = train, pch=19, cex=0.5, horizontal = TRUE, las=2, cex.axis=0.5)
```

```{r, fig.width=10}
top.x <- 20
train$RefAlt <- paste0(train$ref_short, " ", train$alt_short)
var_res <- aggregate(
  train$score,
  by = list(
    RefAlt = train$RefAlt
  ),
  var, na.rm=TRUE
)
colnames(var_res)[ncol(var_res)] <- "Variance"
var_res <- var_res[order(var_res$Variance, decreasing=TRUE),]

train_hv <- train[(train$RefAlt %in% var_res$RefAlt[1:top.x]),]

par(mfrow=c(1,2))
boxplot(score~ref_short+alt_short, 
        data = train_hv, 
        pch=19, cex=0.5, 
        horizontal = TRUE, 
        las=2, cex.axis=0.5, 
        drop=TRUE,
        main = paste0(top.x, " Single AA Changes with highest variance"),
        ylab = "Reference.Alternate"
)

var_res <- var_res[order(var_res$Variance, decreasing=FALSE),]
train_lv <- train[train$RefAlt %in% var_res$RefAlt[1:top.x],]

boxplot(score~ref_short+alt_short, 
        data = train_lv, 
        pch=19, cex=0.5, 
        horizontal = TRUE, 
        las=2, cex.axis=0.5, 
        drop=TRUE,
        main = paste0(top.x, " Single AA Changes with lowest variance"),
        ylab = "Reference.Alternate"
)


```

## Same Ref and Alt

Let's look at the records where the reference and alternate are the same

```{r}
train_ref <- train[train$ref_short == train$alt_short,]

boxplot(
  score~ref_short+alt_short, 
  data = train_ref, 
  pch=19, cex=0.5, horizontal = TRUE, las=2, cex.axis=0.5, drop=TRUE,
  ylab = "Reference.Alternate",
  main = "Reference and Alternate are the same"
)
```
```{r}
tbl_ref <- table(train_ref$scoreset)
tbl_all <- table(train$scoreset)
```

There are `r length(tbl_ref)` out of `r length(tbl_all)` scores sets where there
is at least one variant that is equal to the reference.

Here is the one of the scoresets with a high number of same ref,alt variants

```{r}
train_ref_2 <- train_ref[train_ref$scoreset == "urn:mavedb:00001200-e-1",]
boxplot(
  score~ref_short+alt_short, 
  data = train_ref_2, 
  pch=19, cex=0.5, horizontal = TRUE, las=2, cex.axis=0.5, drop=TRUE,
  ylab = "Reference.Alternate",
  main = "Reference and Alternate are the same\nscoreset 00001200-e-1"
)
```
Let's look at the scoreset with the highest score.

```{r}
train_ref_2 <- train_ref[train_ref$scoreset == "urn:mavedb:00000106-c-1",]
boxplot(
  score~ref_short+alt_short, 
  data = train_ref_2, 
  pch=19, cex=0.5, horizontal = TRUE, las=2, cex.axis=0.5, drop=TRUE,
  ylab = "Reference.Alternate",
  main = "Reference and Alternate are the same\nscoreset 00000106-c-1"
)

```

```{r}
write.csv(train_ref, makeExtFilePath("train", "ref.eq.alt", "csv"), row.names=FALSE)
```


```{r, fig.width=15}
train$RefEQAlt <- train$ref_short == train$alt_short
boxplot(score~pos, data=train[train$scoreset == "urn:mavedb:00001200-e-1",], las=2, drop=TRUE)

train_1220_e_1 <- train[train$scoreset == "urn:mavedb:00001200-e-1",]

train_1220_e_1_rea <- train_1220_e_1[train_1220_e_1$RefEQAlt,]
train_1220_e_1_rnea <- train_1220_e_1[!train_1220_e_1$RefEQAlt,]


grid::grid.newpage()
venn_res<-venn_make2Venn(train_1220_e_1_rea$pos, train_1220_e_1_rnea$pos, label1 = "R=A", label2="R!=A")


```

```{r, fig.height=6, fig.width=6}
train_1220_e_1_187 <- train_1220_e_1[train_1220_e_1$pos == 187,]

colors <- rep("black", nrow(train_1220_e_1_187))
colors[train_1220_e_1_187$RefEQAlt] <- "red"

dotchart(
  x = train_1220_e_1_187$score,
  labels = train_1220_e_1_187$RefAlt, 
  pch=19, color = colors, 
  main="Dotchart of scores of 00001200-e-1 position 187", ylab = "Reference.Alternate", xlab="score"
)

s <- train_1220_e_1_187$score[train_1220_e_1_187$RefEQAlt]
lines(c(s,s),c(-40,40), col="red", lty="dashed")


```

```{r, fig.width=10}
boxplot(score~pos, data=train_1220_e_1_rea, las=2, drop=TRUE, 
main = "Box of scores vs position using ref=alt\nscoreset 00001200-e-1")

```
```{r}
train_1220_e_1_rea[train_1220_e_1_rea$score == min(train_1220_e_1_rea$score),]
```


```{r, fig.height=6, fig.width=6}
train_1220_e_1_187 <- train_1220_e_1[train_1220_e_1$pos == 448,]

colors <- rep("black", nrow(train_1220_e_1_187))
colors[train_1220_e_1_187$RefEQAlt] <- "red"

dotchart(
  x = train_1220_e_1_187$score,
  labels = train_1220_e_1_187$RefAlt, 
  pch=19, color = colors, 
  main="Dotchart of scores of 00001200-e-1 position 448", ylab = "Reference.Alternate", xlab="score"
)

s <- train_1220_e_1_187$score[train_1220_e_1_187$RefEQAlt]
lines(c(s,s),c(-40,40), col="red", lty="dashed")


```
```{r}
train_1220_e_1_rea[train_1220_e_1_rea$score == max(train_1220_e_1_rea$score),]
```
```{r, fig.height=6, fig.width=6}
train_1220_e_1_187 <- train_1220_e_1[train_1220_e_1$pos == 339,]

colors <- rep("black", nrow(train_1220_e_1_187))
colors[train_1220_e_1_187$RefEQAlt] <- "red"

dotchart(
  x = train_1220_e_1_187$score,
  labels = train_1220_e_1_187$RefAlt, 
  pch=19, color = colors, 
  main="Dotchart of scores of 00001200-e-1 position 339", ylab = "Reference.Alternate", xlab="score"
)

s <- train_1220_e_1_187$score[train_1220_e_1_187$RefEQAlt]
lines(c(s,s),c(-40,40), col="red", lty="dashed")


```
